%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  # Isaac Sim IMU noise parameters (simulator IMU is cleaner than real-world)
  accelerometer_noise_density: 4.0000e-4  # [ m / s^2 / sqrt(Hz) ]
  accelerometer_random_walk: 6.0000e-4    # [ m / s^3 / sqrt(Hz) ]
  gyroscope_noise_density: 3.3936e-05     # [ rad / s / sqrt(Hz) ]
  gyroscope_random_walk: 3.8786e-06       # [ rad / s^2 / sqrt(Hz) ]
  rostopic: /telemetry/imu
  time_offset: 0.0
  update_rate: 50.0 # Isaac Sim IMU at ~50 Hz
  model: "kalibr"
  Tw:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  R_IMUtoGYRO:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  Ta:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  R_IMUtoACC:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  Tg:
    - [ 0.0, 0.0, 0.0 ]
    - [ 0.0, 0.0, 0.0 ]
    - [ 0.0, 0.0, 0.0 ]
